# Base Configuration for QuantBot Trading System
# ==============================================
# This file contains default settings shared across all environments

# Application Settings
app_name: "QuantBot"
app_version: "1.0.0"
timezone: "US/Eastern"
debug: false

# Cache Configuration
cache_enabled: true
cache_ttl_seconds: 3600  # 1 hour
cache_max_size_mb: 512

# Performance Settings
async_enabled: true
max_concurrent_requests: 10
worker_threads: 4

# Database Configuration (will be overridden per environment)
database:
  host: "localhost"
  port: 5432
  username: "quantbot"
  password: "SECURE:database_password"
  database: "quantbot"
  pool_size: 10
  ssl_mode: "prefer"

# Trading Configuration
trading:
  max_position_size: 0.1        # 10% of portfolio max
  max_daily_loss: 1000.0        # $1000 max daily loss
  risk_free_rate: 0.05          # 5% risk-free rate
  commission_per_contract: 1.0  # $1.00 per options contract
  slippage_bps: 5              # 5 basis points slippage

# Data Sources Configuration
data_sources:
  # API Keys (use SECURE: prefix for encrypted storage)
  polygon_api_key: "SECURE:OROZxfRr0KoSI6ilsYZiyp8oTRHq478Y"
  finnhub_api_key: "SECURE:d1vm8l1r01qqgeembco0d1vm8l1r01qqgeembcog"
  alpha_vantage_api_key: "SECURE:583JT6TWFMIKDGVN"
  newsapi_key: "SECURE:47007e0b8de74863b15d79bb83df5976"
  openweather_api_key: "SECURE:880b3b206c79f32c79970bfd338bb555"
  fred_api_key: "SECURE:1e4aaa2f7308fbef174ff5cb1e2b8460 "
  stocktwits_token: "SECURE:stocktwits_token"
  gnews_key: "SECURE:00525f2193cd8d6cca6219ba869d02ea"
  reddit_client_id: "SECURE:reddit_client_id"
  reddit_client_secret: "SECURE:reddit_client_secret"
  openai_api_key: "SECURE:sk-proj-LNFQqPCzvMP63moU0al8Ut_qPh3AvIYg0YF3Exn2ysdr2FikZaf4dn95M_7vm33IFX-inU8$"
  
  # Rate Limiting Configuration
  rate_limits:
    polygon:
      requests_per_minute: 300
      requests_per_hour: 18000
      requests_per_day: 100000
      backoff_factor: 1.5
      max_retries: 3
      timeout_seconds: 30
      
    finnhub:
      requests_per_minute: 60
      requests_per_hour: 3600
      requests_per_day: 50000
      backoff_factor: 2.0
      max_retries: 3
      timeout_seconds: 15
      
    alpha_vantage:
      requests_per_minute: 5
      requests_per_hour: 300
      requests_per_day: 500
      backoff_factor: 2.0
      max_retries: 5
      timeout_seconds: 30
      
    newsapi:
      requests_per_minute: 100
      requests_per_hour: 1000
      requests_per_day: 1000
      backoff_factor: 1.5
      max_retries: 3
      timeout_seconds: 10
      
    openweather:
      requests_per_minute: 60
      requests_per_hour: 1000
      requests_per_day: 1000
      backoff_factor: 1.5
      max_retries: 3
      timeout_seconds: 10
      
    fred:
      requests_per_minute: 120
      requests_per_hour: 1000
      requests_per_day: 100000
      backoff_factor: 1.2
      max_retries: 3
      timeout_seconds: 15
      
    stocktwits:
      requests_per_minute: 200
      requests_per_hour: 400
      requests_per_day: 400
      backoff_factor: 2.0
      max_retries: 2
      timeout_seconds: 10
      
    gnews:
      requests_per_minute: 10
      requests_per_hour: 100
      requests_per_day: 100
      backoff_factor: 3.0
      max_retries: 3
      timeout_seconds: 20
      
    reddit:
      requests_per_minute: 60
      requests_per_hour: 600
      requests_per_day: 1000
      backoff_factor: 2.0
      max_retries: 3
      timeout_seconds: 15

# Monitoring Configuration
monitoring:
  log_level: "INFO"
  enable_metrics: true
  metrics_port: 8080
  grafana_enabled: false
  prometheus_enabled: false
  alert_webhook_url: null
